### PR TITLE
Improving test_csr and test_dia

### LINKED ISSUE #5: test cases
test cases in `arc/matrices/tests` can be greatly improved.

### PR DESCRIPTION
**Pull request by lautalaserna**
Added limit tests and more intuitive assets.

Closes #5

### CODE REVIEW

**Comment by Bchass** [comment]
Hi @lautalaserna, thanks for this! Could you rebase your branch or resolve the conflicts in this PR? It's currently blocking from the jobs running for this PR. 

Also, can you update your comment to add something like "Closes <insert issue link here>"? This will link the PR to the issue and close the issue automatically once merged. 

You can find more here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by lautalaserna** [comment]
Done! Conflicts are resolved and the PR is linked to the issue.

**Comment by Bchass** [comment]
> Done! Conflicts are resolved and the PR is linked to the issue.

Thanks! Could you rebase one more time? I dropped Flake8 from the jobs as I realized it's going to cause too many issues and the jobs for this PR still hold the requirements for Flake8.

**Comment by Bchass** [comment]
> Done! Conflicts are resolved and the PR is linked to the issue.

Could you rebase one more time? Dropped Flake8 requirements, but the jobs in this PR are still reading in the old configuration.

**Pull request closed without merging**
